# CAGE Preprocessing

In [2]:
import pandas as pd

In [5]:
X1_train_info = pd.read_table("../CAGE-train/X1_train_info.tsv")
X1_train_y = pd.read_table("../CAGE-train/X1_train_y.tsv")
X1_val_info = pd.read_table("../CAGE-train/X1_val_info.tsv")
X1_val_y = pd.read_table("../CAGE-train/X1_val_y.tsv")
X2_train_info = pd.read_table("../CAGE-train/X2_train_info.tsv")
X2_train_y = pd.read_table("../CAGE-train/X1_train_y.tsv")
X2_val_info = pd.read_table("../CAGE-train/X2_val_info.tsv")
X2_val_y = pd.read_table("../CAGE-train/X1_val_y.tsv")
X3_test_info = pd.read_table("../CAGE-train/X3_test_info.tsv")

In [13]:
X1_train = X1_train_info.set_index('gene_name').join(X1_train_y.set_index('gene_name'))
X1_val = X1_val_info.set_index('gene_name').join(X1_val_y.set_index('gene_name'))
X2_train = X2_train_info.set_index('gene_name').join(X2_train_y.set_index('gene_name'))
X2_val = X2_val_info.set_index('gene_name').join(X2_val_y.set_index('gene_name'))

In [14]:
X1_train

,chr,gene_start,gene_end,TSS_start,TSS_end,strand,gex
gene_name,,,,,,,
SLC20A1,chr2,112645939,112663825,112658362,112658412,+,0.000000
C11orf58,chr11,16613132,16758340,16738643,16738693,+,2239.103328
ZSCAN9,chr6,28224886,28233487,28225263,28225313,+,19.798064
CD19,chr16,28931965,28939342,28931956,28932006,+,411.530623
TMEM123,chr11,102396332,102470384,102452789,102452839,-,34.214129
...,...,...,...,...,...,...,...
ACOX1,chr17,75941507,75979177,75955565,75955589,-,0.000000
MLXIP,chr12,122078756,122147344,122127887,122127937,+,0.000000
ASGR2,chr17,7101322,7115700,7114614,7114653,-,0.000000
OR5A1,chr11,59436469,59451380,59443143,59443193,+,0.000000
TLR3,chr4,186069155,186088073,186069154,186069204,+,0.480536